### ISSUE TITLE
Opening URL with custom protocol handler does not work (xdg-open)

### ISSUE THREAD

**Issue by moocerdata** [learn-co-students/welcome-to-learn-5-welcome-000#5]
I just installed the Learn IDE and tried opening a "lab" from the "Trial course" website. It tries to open a URL `learn-ide://learn-ide/welcome-to-learn-5-welcome-000`. It seems when the learn IDE is installed it does not properly register in my Ubuntu system for handling such URLs and thus I cannot even start with the very first trial course to try out the IDE and the platform or its concept. I am using Chromium (and will not install Google Chrom …) version `Version 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)`

What can be done about this?

**Comment by gj** [comment]
Hi @moocerdata, @cacarr-pdxweb, @sauravjaiswalsj, @fznfu, and @Keyproco !

The `Open` button doesn't work on Linux, so you'll have to run the `learn open` command in your IDE terminal to open new lessons. Sorry about that!
