### ISSUE TITLE
Atom & Learn IDE don't play nice

### ISSUE THREAD

**Issue by gregimba** [learn-co-students/welcome-to-learn-5-welcome-000#7]
If you have Atom already installed when you open the Learn IDE my filebrowser was not showing up.
Uninstalling Atom solved this problem.

```
rm ~/Applications/Atom.app #delete app
rm -rf ~/.atom #delete dotfiles
rm /usr/local/bin/atom
rm /usr/local/bin/apm
rm ~/Library/Preferences/com.github.atom.plist
```

**Comment by gj** [comment]
Hi @gregimba, sounds like you got this solved. Sorry for the confusion!
